services:
  cli:
    build: '.docker'
    volumes:
      - '.:/app'
      - '.docker/php.ini:/usr/local/etc/php'
      - '.docker/xdebug.ini:/usr/local/etc/php/conf.d/'

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_TCP_PORT: ${DB_PORT}
    ports:
      - '3306:${DB_PORT}'
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
